### ISSUE TITLE
Error: AnimationController.dispose() called more than once.

### ISSUE THREAD

**Issue by andre-ab** [payam-zahedi/toastification#97] opened 2024-04-12 17:24 UTC
**Flutter (Channel stable, 3.19.2, on Ubuntu 22.04.4 LTS 6.5.0-27-generic, locale pt_BR.UTF-8)**
**toastification: ^1.2.1**

I have this class:
```
import 'package:flutter/material.dart';
import 'package:toastification/toastification.dart';


class Talert {
  /*  static final Talert _instance = Talert._internal();
  Talert._internal();
  factory Talert() => _instance; */
  //
  void _tost({
    required BuildContext context,
    String? title,
    int? time,
    required ToastificationType type,
  }) {
    toastification.show(
      type: type,
      style: ToastificationStyle.minimal,
      alignment: Alignment.topCenter,
      context: context,
      title: Text(title ?? 'Title'),
      autoCloseDuration: Duration(seconds: time ?? 3),
    );
  }

  void inf({required BuildContext context, String? title, int? time}) {
    _tost(
        context: context,
        title: title,
        time: time,
        type: ToastificationType.info);
  }

  void success({required BuildContext context, String? title, int? time}) {
    _tost(
        context: context,
        title: title,
        time: time,
        type: ToastificationType.success);
  }

  void warning({required BuildContext context, String? title, int? time}) {
    _tost(
        context: context,
        title: title,
        time: time,
        type: ToastificationType.warning);
  }

  void error({required BuildContext context, String? title, int? time}) {
    _tost(
      context: context,
      title: title,
      time: time ?? 4,
      type: ToastificationType.error,
    );
  }
}

```
Call:
  `final toast = Talert();`
I call the data like this: 
` toast.error(context: context, title: 'Hi, I'm toastification');`

error:
![image](https://github.com/payam-zahedi/toastification/assets/10952239/6fc6dff4-af91-475e-864e-48f13b066ac3)

**Comment by WajdiMuh** [comment] 2024-04-14 18:16
I have the same issue on my end and from what i noticed is that this happens when autoclose is used and when the duration to auto close is set to a longer value than the animation duration and therefor it will attempt to call dispose on an animation that was already finished

**Comment by pistalibre** [comment] 2024-04-20 23:43
I have also the same issue. I have tried with the example code of the package but still get the error. I tried disabling the auto close animation but didn't work. Also tried changing the times of both animations but still get the error. I don't quite know what to do and it is a shame because the package is awesome.

**Comment by KeithEyreDFM** [comment] 2024-04-22 14:18
I'm also getting this but I thought it was when I displayed it multiple times in a row allowing them to stack...  Pleas fix this

**Comment by payam-zahedi** [comment] 2024-04-22 14:27
Hey guys 

This issue is a duplicate of #54 
I will close it and continue it there

**Closed by payam-zahedi** 2024-04-22 14:27 UTC
Labels: question
