### ISSUE TITLE
AnimationController.dispose() called more than once. on multiple action show

### ISSUE THREAD

**Issue by indratrisnar** [payam-zahedi/toastification#132] opened 2024-09-07 04:26 UTC
my app got freeze when show toastification

i use toastification with context, when i click action and trigger show toastification. (first time ok)
but for next toast, my app got freeze and throw exception

this should be fine, based on flow code i wrote
class AppInfo {
  static error(BuildContext context, String message) {
    toastification.show(
      context: context,
      title: Text(message),
      autoCloseDuration: const Duration(milliseconds: 2500),
      closeButtonShowType: CloseButtonShowType.none,
    );
  }
}

void addNew() {
...
if (xFile.path == '') {
      AppInfo.error(context, 'No Image Selected');
      return;
}
...
}

![image](https://github.com/user-attachments/assets/1d7e0e6e-9f1b-4563-b68b-7d79ef04f1ea)

![image](https://github.com/user-attachments/assets/7eb6407a-8deb-4c5c-9f27-ff104b1bc42a)

 - OS: Web
 - Flutter Version: 3.24.1
 - Toastification Version: 8.2.8

**Comment by AntonioAEMartins** [comment] 2024-09-08 18:32
@indratrisnar , I’ve also encountered this issue frequently in my app. I’m trying to resolve it without altering the library’s behavior. Do you know how I can assign this issue to myself to indicate that I’m working on it?

**Comment by AntonioAEMartins** [comment] 2024-09-08 20:50
@indratrisnar, I’m investigating this issue and have found two scenarios that might align with your experience. Could you confirm if these match what you’ve observed?

Multiple Toasts: When several toasts are shown, there's an intermittent occurrence of the AnimationController.dispose() error. It happens inconsistently.

Manual Toast Dismissal: When a toast is manually closed by the user, and then the animation duration ends, the same error is thrown (AnimationController.dispose()).

Does this align with your findings?

**Comment by indratrisnar** [comment] 2024-09-08 22:58
Yes, it does.

Pada Sen, 9 Sep 2024 03.50, Antônio A E Martins ***@***.***>
menulis:

**Comment by payam-zahedi** [comment] 2024-09-09 19:09
Hey @AntonioAEMartins 

Nope, you don't need to do anything specific.

You said it here, and it's yours now 😄 

Feel free to Open your PR and let me know if you need anything

**Comment by Jesse-Abruzzo** [comment] 2024-09-09 22:48
im having this same issue. debugging always happens the first time the toast is called.

**Comment by mhdabdelrhman** [comment] 2024-09-10 18:30
I am having the same issue, always when the toast is closed manually or auto.

**Comment by AntonioAEMartins** [comment] 2024-09-10 20:15
Hi @Jesse-Abruzzo, @mhdabdelrhman, and @indratrisnar,

I wanted to update you on the bug discovery related to the duplicate disposal of toasts. After some investigation, I’ve identified multiple scenarios that could be contributing to this issue.

To help me better understand the configurations you're using and narrow down the root cause, could you please answer the following questions?

1. Are you using custom toasts or standard ones?
2. Do you have a progress indicator enabled for the toasts?

Thanks for your input! This will help us get closer to resolving the problem.

**Comment by AntonioAEMartins** [comment] 2024-09-10 22:02
Hi @Jesse-Abruzzo, @mhdabdelrhman, and @indratrisnar,

I believe I've identified and fixed the bug. I’d like you all to test the fix in your applications.

Please download my branch issue-132, then update your dependency path to point to the locally downloaded version. After that, compile your app and let me know how it goes.

Looking forward to your feedback!

I've tested the changes locally in my projects, and could not reproduce the AnimationController.dispose() called more than once.

**Comment by mhdabdelrhman** [comment] 2024-09-11 05:59
Hi @AntonioAEMartins ,

I downloaded the project, updated the dependencies, and tested my application. Everything is functioning properly now, and the issue has been resolved.

Thank you.

**Comment by AntonioAEMartins** [comment] 2024-09-11 12:56
@mhdabdelrhman Nice to hear that. I'm going to open a pull request, to correct and finally this issue.

**Closed** 2024-09-14 11:42 UTC
Labels: bug
